/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as DrinksRouteImport } from './routes/drinks'
import { Route as GroceryRouteImport } from './routes/grocery'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAccountsRouteImport } from './routes/admin/accounts'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminGroceryRouteImport } from './routes/admin/grocery'
import { Route as AdminInventoryRouteImport } from './routes/admin/inventory'
import { Route as AdminLiquorRouteImport } from './routes/admin/liquor'
import { Route as AdminMarketingRouteImport } from './routes/admin/marketing'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminRidersRouteImport } from './routes/admin/riders'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminShippingRouteImport } from './routes/admin/shipping'
import { Route as AdminStaffRouteImport } from './routes/admin/staff'
import { Route as AdminTaxonomyRouteImport } from './routes/admin/taxonomy'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DrinksRoute = DrinksRouteImport.update({
  id: '/drinks',
  path: '/drinks',
  getParentRoute: () => rootRouteImport,
} as any)
const GroceryRoute = GroceryRouteImport.update({
  id: '/grocery',
  path: '/grocery',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAccountsRoute = AdminAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGroceryRoute = AdminGroceryRouteImport.update({
  id: '/grocery',
  path: '/grocery',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLiquorRoute = AdminLiquorRouteImport.update({
  id: '/liquor',
  path: '/liquor',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMarketingRoute = AdminMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRidersRoute = AdminRidersRouteImport.update({
  id: '/riders',
  path: '/riders',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminShippingRoute = AdminShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTaxonomyRoute = AdminTaxonomyRouteImport.update({
  id: '/taxonomy',
  path: '/taxonomy',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/drinks': typeof DrinksRoute
  '/grocery': typeof GroceryRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/grocery': typeof AdminGroceryRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/liquor': typeof AdminLiquorRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/riders': typeof AdminRidersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/taxonomy': typeof AdminTaxonomyRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/drinks': typeof DrinksRoute
  '/grocery': typeof GroceryRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/grocery': typeof AdminGroceryRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/liquor': typeof AdminLiquorRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/riders': typeof AdminRidersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/taxonomy': typeof AdminTaxonomyRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/drinks': typeof DrinksRoute
  '/grocery': typeof GroceryRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/grocery': typeof AdminGroceryRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/liquor': typeof AdminLiquorRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/riders': typeof AdminRidersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/taxonomy': typeof AdminTaxonomyRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/drinks'
    | '/grocery'
    | '/login'
    | '/signup'
    | '/admin/accounts'
    | '/admin/customers'
    | '/admin/grocery'
    | '/admin/inventory'
    | '/admin/liquor'
    | '/admin/marketing'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/riders'
    | '/admin/settings'
    | '/admin/shipping'
    | '/admin/staff'
    | '/admin/taxonomy'
    | '/admin/users'
    | '/admin/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/drinks'
    | '/grocery'
    | '/login'
    | '/signup'
    | '/admin/accounts'
    | '/admin/customers'
    | '/admin/grocery'
    | '/admin/inventory'
    | '/admin/liquor'
    | '/admin/marketing'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/riders'
    | '/admin/settings'
    | '/admin/shipping'
    | '/admin/staff'
    | '/admin/taxonomy'
    | '/admin/users'
    | '/admin'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/drinks'
    | '/grocery'
    | '/login'
    | '/signup'
    | '/admin/accounts'
    | '/admin/customers'
    | '/admin/grocery'
    | '/admin/inventory'
    | '/admin/liquor'
    | '/admin/marketing'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/riders'
    | '/admin/settings'
    | '/admin/shipping'
    | '/admin/staff'
    | '/admin/taxonomy'
    | '/admin/users'
    | '/admin/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  DrinksRoute: typeof DrinksRoute
  GroceryRoute: typeof GroceryRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drinks': {
      id: '/drinks'
      path: '/drinks'
      fullPath: '/drinks'
      preLoaderRoute: typeof DrinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grocery': {
      id: '/grocery'
      path: '/grocery'
      fullPath: '/grocery'
      preLoaderRoute: typeof GroceryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/accounts': {
      id: '/admin/accounts'
      path: '/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AdminAccountsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/grocery': {
      id: '/admin/grocery'
      path: '/grocery'
      fullPath: '/admin/grocery'
      preLoaderRoute: typeof AdminGroceryRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/liquor': {
      id: '/admin/liquor'
      path: '/liquor'
      fullPath: '/admin/liquor'
      preLoaderRoute: typeof AdminLiquorRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/marketing': {
      id: '/admin/marketing'
      path: '/marketing'
      fullPath: '/admin/marketing'
      preLoaderRoute: typeof AdminMarketingRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/riders': {
      id: '/admin/riders'
      path: '/riders'
      fullPath: '/admin/riders'
      preLoaderRoute: typeof AdminRidersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/shipping': {
      id: '/admin/shipping'
      path: '/shipping'
      fullPath: '/admin/shipping'
      preLoaderRoute: typeof AdminShippingRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/taxonomy': {
      id: '/admin/taxonomy'
      path: '/taxonomy'
      fullPath: '/admin/taxonomy'
      preLoaderRoute: typeof AdminTaxonomyRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAccountsRoute: typeof AdminAccountsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminGroceryRoute: typeof AdminGroceryRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminLiquorRoute: typeof AdminLiquorRoute
  AdminMarketingRoute: typeof AdminMarketingRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRidersRoute: typeof AdminRidersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminShippingRoute: typeof AdminShippingRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminTaxonomyRoute: typeof AdminTaxonomyRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAccountsRoute: AdminAccountsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminGroceryRoute: AdminGroceryRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminLiquorRoute: AdminLiquorRoute,
  AdminMarketingRoute: AdminMarketingRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRidersRoute: AdminRidersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminShippingRoute: AdminShippingRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminTaxonomyRoute: AdminTaxonomyRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  DrinksRoute: DrinksRoute,
  GroceryRoute: GroceryRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
